BangCrush/BankAI-Frontend

.storybook/main.js, .storybook/preview.js, package-lock.json, package.json, src/App.css, src/lib/store.js, src/stories/atoms/longButton/index.js, src/stories/atoms/longButton/index.stories.jsx
<br>
📌 관련 이슈
---
<br>
🧭 작업 브랜치
---
<br>
📚 작업 내용
---
<br>
📝 상세 설명
---
<br>
=> [test] 스토리북 테스트

src/stories/molecules/product/index.js, src/stories/molecules/product/index.stories.jsx, src/stories/organisms/productList/index.js, src/stories/organisms/productList/index.stories.jsx, tailwind.config.js
=> [feat] 상품 컴포넌트

src/stories/atoms/accountItem/index.js, src/stories/atoms/accountItem/index.stories.jsx, src/stories/atoms/mainCarousel/index.js, src/stories/atoms/mainCarousel/index.stories.jsx, src/stories/atoms/mediumButton/index.js, tailwind.config.js
=> [feat] 캐러셀 요쇼, 계좌 목록 요소 컴포넌트

package.json
=> [fix] craco로 인한 오류사항 변경

package-lock.json, package.json, src/index.js
- Module not found: Error: You attempted to import react which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.  #50
- https://github.com/mmazzarolo/react-native-universal-monorepo/issues/50
=> [feat] node modules 의존성 충돌 문제 해결

src/stories/molecules/accHistory/index.js, src/stories/molecules/accHistory/index.stories.jsx, src/stories/molecules/accountItem/index.js, src/stories/molecules/accountItem/index.stories.jsx, src/stories/molecules/mainCarousel/index.js, src/stories/molecules/mainCarousel/index.stories.jsx, src/stories/molecules/prodButtons/index.js, src/stories/molecules/prodButtons/index.stories.jsx
상품 종류 버튼을 만들었습니다~!!
기존에 만들었던 컴포넌트 함수명 첫글자를 대문자로 바꾸기도 했습니다~!!
- closes #17
=> [feat] 상품 종류 버튼

.github/workflows/Github-Actions-FE.yml
.github에 Github Actions yml 파일 작성
- closes
organization 의 main branch 대상 push와 PR close 에 반응하여 서버에 코드 Integration / Deploy
=> [add] Github Actions를 통한 CI/CD 구축

src/stories/atoms/input/index.js, src/stories/atoms/mediumButton/index.js, src/stories/molecules/accHistory/index.js, src/stories/molecules/accountItem/index.js, src/stories/molecules/mainCarousel/index.js, src/stories/molecules/prodButtons/index.js
longButton
shortButton
mediumButton
accHistory
accountItem
mainCarousel
prodButtons
searchBar
input
사이즈 미세조정 함
- closes #22
=> [design] 앱 뷰 -> 태블랫 뷰 중간 변경

src/stories/atoms/pwdNum/index.js, src/stories/molecules/pwdLine/index.js, src/stories/molecules/pwdLine/index.stories.jsx, src/stories/organisms/pwdKeyboard/index.js, src/stories/organisms/pwdKeyboard/index.stories.jsx
#28 - Processing
+ Number Randomize 기능 구현
=> [design] Password Keyword 기반 코드 작성

src/stories/molecules/prodType/index.js, src/stories/molecules/prodType/index.stories.jsx, src/stories/molecules/product/index.js, src/stories/molecules/product/index.stories.jsx, src/stories/organisms/productList/index.js, src/stories/organisms/productList/index.stories.jsx, src/stories/pages/product/ProductPage.jsx, src/stories/templates/MainLayout.js, tailwind.config.js
- closes #31 
- 상품 목록 컴포넌트 (마지막 요소 아래선 안보이게 수정)
- 상품 페이지
=> [feat] 상품 목록 페이지

src/stories/molecules/headerBar/index.js, src/stories/molecules/prodDetailItem/index.js, src/stories/molecules/prodDetailItem/index.stories.jsx, src/stories/page/prodDetail/index.js, src/stories/page/prodDetail/index.stories.jsx
이 부분은 molecules에 컴포넌트로 빼놨음
- closes #35
=> [design] 상품 상세 페이지

src/stories/molecules/mediumInput/index.js, src/stories/molecules/mediumInput/index.stories.jsx, src/stories/molecules/warning/index.js, src/stories/molecules/warning/index.stories.jsx
- closes #37 
- closes #38 
- active: 입력 받기 활성화 상태이면 true, 아니면 false
=> [design] medium input 컴포넌트, 경고 컴포넌트

src/stories/molecules/bottomStickyButton/index.js, src/stories/molecules/bottomStickyButton/index.stories.jsx
- closes #39 
우리 서비스 화면 높이 정하면 좋을 듯
=> [design] 하단 고정 버튼 컴포넌트

package-lock.json, package.json, src/stories/atoms/pwdDot/index.js, src/stories/atoms/pwdDot/index.stories.jsx, src/stories/atoms/pwdNum/index.js, src/stories/molecules/pwdDots/index.js, src/stories/molecules/pwdDots/index.stories.jsx, src/stories/molecules/pwdLine/index.js, src/stories/organisms/pwdKeyboard/index.js, src/stories/pages/pwdPage/index.js, src/stories/pages/pwdPage/index.stories.jsx
Password 입력 Keyboard 화면 구현
- closes
Pwd입력을 위한 Atoms와 Molecules 작성
Organisms와 Page 단위 작업 및 각 컴포넌트 연결 완료
버튼 클릭 시 키 배열 무작위로 배치 / 입력 내용 길이에 맞게 Dot과 상호작용하도록 구현
=> [feat] 비밀번호 입력 모달 페이지 작성

src/App.js, src/routes/subLayoutRouter.js, src/stories/molecules/accHistory/index.js, src/stories/molecules/accHistory/index.stories.jsx, src/stories/molecules/blueHeaderBar/index.js, src/stories/molecules/blueHeaderBar/index.stories.jsx, src/stories/pages/accHistoryPage/index.js
- closes #48 
서브레이아웃라우터에 import 된 acchistory 뭐시기 나중에 지워야됨
=> [design] 계좌 상세 내역 페이지

.gitignore, src/stories/molecules/pwdLine/index.js, src/stories/organisms/bottomSheet/index.js, src/stories/organisms/bottomSheet/index.stories.jsx
=> [design] 바텀 시트 컴포넌트/기능 구현

package-lock.json, package.json, src/stories/pages/IdentifyPage/index.jsx
=> [fix] use-immer 모듈 버그 해결

src/stories/molecules/mainCarousel/index.js
캐러셀 버튼 디자인 수정 및 크기 변경 적용
- closes #54 
https://react-slick.neostack.com/docs/example/custom-arrows
=> [design] 캐러셀 Left / Right Arrow 수정

src/stories/pages/mainPage/index.jsx
=> [fix] > 문자 오류 &gt로 수정

src/hooks/useValid.js, src/routes/subLayoutRouter.js, src/stories/atoms/input/index.js, src/stories/atoms/input/index.stories.jsx, src/stories/pages/joinPage/index.jsx, src/stories/pages/joinPage/page1.jsx, tailwind.config.js
=> [feat] 회원가입 유효성 체크

src/stories/pages/joinPage/index.jsx, src/stories/pages/joinPage/page3.jsx
- closes #64 
- 사용자 아이디 중복체크는 후에 서버통신 과정에서 체크할 예정입니다
=> [feat] 회원가입 마지막 단계

src/routes/noLayoutRouter.js, src/routes/subLayoutRouter.js, src/stories/atoms/title/index.js, src/stories/molecules/headerBar/index.js, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page1.jsx, src/stories/pages/loanPage/page2.jsx
- closes #66 
- closes #68 
- 목 데이터 이용했습니다.
=> [feat] 대출가입 페이지 - 1단계, 2단계

src/stories/molecules/transferInfo/index.js, src/stories/molecules/transferInfo/index.stories.jsx, src/stories/pages/transferCheckPage/index.js, src/stories/pages/transferCheckPage/index.stories.jsx
=> [design] 계좌이체 내용 확인 페이지 구현

src/routes/subLayoutRouter.js, src/stories/pages/transferPage/index.js, src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js
=> [feat] 계좌이체 화면 및 유효성 검사

src/stories/molecules/loanInfo/index.js, src/stories/molecules/loanInfo/index.stories.jsx, src/stories/organisms/bottomSheet/index.stories.jsx, src/stories/pages/loanCheckPage/index.js, src/stories/pages/loanCheckPage/index.stories.jsx
=> [design] 대출 신청 확인 페이지 구현

src/stories/pages/loanPage/page2.jsx
=> [feat] (대출) 매월 상환 금액 명시

src/stories/organisms/prodBenefit/index.js, src/stories/organisms/prodBenefit/index.stories.jsx, src/stories/page/prodDetail/index.js
- closes #76 
issue는 [design]이라고 써놓고 commit은 [feat]으로 함 ㅈㅅ,,ㅎㅎ,,,
금액 입력란에 숫자 외 문자 검증 빼먹음 나중에 추가 하겠음
=> [feat] 상품 상세 페이지 내에 들어갈 컴포넌트

src/constants/products.js, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page2.jsx
- closes #80 
- 원금균등상환
- 만기일시상환
=> [feat] 대출 상환방식에 따른 납부금액 계산

src/constants/products.js, src/stories/atoms/repayDesc/index.js, src/stories/atoms/repayDesc/index.stories.jsx, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page2.jsx
- closes #86 
- 원금균등상환 설명
- 만기일시상환 설명
=> [design] 상환방식 설명 토글  컴포넌트

src/stories/atoms/repayDesc/index.stories.jsx
=> [fix] 스토리북 빌드 에러

src/routes/noLayoutRouter.js, src/stories/organisms/prodBenefit/index.js, src/stories/pages/prodDetail/index.js, src/stories/pages/prodDetail/index.stories.jsx
=> [feat] 대출 상품 상세 페이지 라우팅 및  대출 가입 페이지로 연결

src/mocks/mockData.js, src/routes/subLayoutRouter.js, src/stories/molecules/mediumInput/index.js, src/stories/molecules/mediumInput/index.stories.jsx, src/stories/pages/savingsPage/index.jsx
=> [design] 적금가입 페이지

src/mocks/mockData.js, src/stories/atoms/accSelectBox/index.js, src/stories/atoms/accSelectBox/index.stories.jsx, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page3.jsx, src/stories/pages/savingsPage/index.jsx, src/stories/pages/savingsPage/page1.jsx, src/stories/pages/savingsPage/page2.jsx
=> [feat] 출금 계좌 설정 페이지

src/stories/atoms/selectBox/index.js, src/stories/pages/loanPage/page3.jsx, src/stories/pages/savingsPage/index.jsx, src/stories/pages/savingsPage/page3.jsx
=> [feat] 자동이체일 선택 페이지

src/stories/pages/savingsPage/index.jsx, src/stories/pages/savingsPage/page3.jsx
=> [design] 자동이체 한도 안내 메세지

src/stories/pages/bottomPages/transferWarningPage/index.js
=> [fix] 계좌이체 Warning Page 버튼 활성화

src/stories/atoms/selectBox/index.js, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page3.jsx, src/stories/pages/loanPage/page4.jsx, src/stories/pages/loanPage/page5.jsx, src/stories/pages/loanPage/page6.jsx, src/stories/pages/savingsPage/page3.jsx
=> [design] 대출 신용도 확인 페이지 - 직업명

src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js
relative 옵션 삭제를 통한 페이지 레이아웃 Bug fix
- closes #110
=> [fix] relative 옵션 삭제를 통한 계좌이체 페이지 Layout 개선

src/stories/pages/joinPage/page3.jsx, src/stories/pages/loginPage/index.js
=> [feat] 로그인, 회원가입 페이지 연결

src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/pages/joinPage/page1.jsx, src/stories/pages/joinPage/page3.jsx
- closes #116 
- 전송 버튼 누르면 인증번호 입력하는 칸이 나옴
=> [feat] 이메일 전송 api

src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/atoms/input/index.js, src/stories/atoms/shortButton/index.js, src/stories/pages/joinPage/page1.jsx
=> [feat] 이메일 중복체크

src/stories/pages/joinPage/page1.jsx
=> [feat] 메일 코드 인증 확인

src/stories/pages/joinPage/page2.jsx, src/stories/pages/zipcodePage/index.jsx
=> [feat] 우편번호 자동 로딩

src/api/userApi.js, src/hooks/queries/userQueries.js, src/hooks/useValid.js, src/stories/pages/joinPage/index.jsx, src/stories/pages/joinPage/page1.jsx, src/stories/pages/joinPage/page2.jsx, src/stories/pages/joinPage/page3.jsx
=> [feat] 회원가입 서버통신

src/routes/noLayoutRouter.js, src/stories/molecules/mainCarousel/index.js, src/stories/molecules/totalAcc/index.js, src/stories/pages/mainPage/index.jsx
=> [design] ui 디자인 수정

src/api/productApi.js, src/constants/products.js, src/hooks/queries/productQueries.js, src/stories/organisms/productList/index.js, src/stories/pages/productPage/index.jsx
=> [feat] 전체 상품 조회 api 통신

src/api/userApi.js, src/stories/pages/joinPage/page1.jsx, src/stories/pages/joinPage/page3.jsx
=> [fix] 회원가입 요청 실패 오류 해결

src/api/productApi.js, src/hooks/queries/productQueries.js, src/routes/noLayoutRouter.js, src/stories/molecules/prodDetailItem/index.js, src/stories/organisms/productList/index.js, src/stories/pages/prodDetail/index.js, src/stories/pages/productPage/index.jsx
=> [feat] 상품 상세 조회 api 통신

src/hooks/queries/userQueries.js, src/stories/pages/loginPage/index.jsx
=> [feat] 로그인 성공/실패 case 처리

src/api/accountApi.js, src/hooks/queries/accountQueries.js, src/stories/molecules/mainCarousel/index.js, src/stories/molecules/mainCarousel/index.stories.jsx, src/stories/pages/mainPage/index.jsx
- 캐러셀에 띄우는 계좌 목록
- closes #138
=> [feat] 내 계좌 목록 조회 api 통신

src/api/accountApi.js, src/hooks/queries/accountQueries.js, src/routes/noLayoutRouter.js, src/stories/molecules/totalAcc/index.js, src/stories/pages/loginPage/index.jsx, src/stories/pages/mainPage/index.jsx
=> [feat] 총 자산합계 조회 api 통신

package-lock.json, package.json, src/App.js, src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/organisms/productList/index.js, src/stories/pages/loginPage/index.jsx, src/stories/pages/mainPage/index.jsx, src/stories/pages/myPage/index.js, src/stories/pages/productPage/index.jsx
=> [feat] 사용자 로그인 api 통신

src/App.js, src/api/accountApi.js, src/api/userApi.js, src/hooks/queries/userQueries.js
=> [feat] 로그인 유무에 따른 api 인가 방식 변경

src/api/userApi.js, src/stories/molecules/mainCarousel/index.js, src/stories/organisms/prodContainer/index.js, src/stories/pages/mainPage/index.jsx, src/stories/pages/myPage/index.js, src/stories/pages/productPage/index.jsx
=> [fix] 자잘한 경고문, key 값 설정

src/hooks/queries/accountQueries.js, src/routes/noLayoutRouter.js, src/stories/molecules/accountItem/index.js, src/stories/pages/accountPage/index.jsx, src/stories/pages/mainPage/index.jsx
=> [feat] 전체 계좌 리스트 페이지, api 통신

src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/atoms/shortButton/index.js, src/stories/pages/IdentifyPage/index.jsx, src/stories/pages/IdentifyPage/page1.jsx, src/stories/pages/IdentifyPage/page2.jsx, src/stories/pages/IdentifyPage/page3.jsx
=> [feat] 휴대폰 인증번호 발송

src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/pages/IdentifyPage/page3.jsx
=> [feat] 문자 본인인증 확인 api 통신

src/hooks/queries/userQueries.js, src/stories/pages/IdentifyPage/page3.jsx
=> [fix] 휴대폰 인증코드 불일치 버그 수정

src/stories/atoms/inherentInput/index.js, src/stories/pages/IdentifyPage/index.jsx, src/stories/pages/IdentifyPage/page1.jsx, src/stories/pages/IdentifyPage/page2.jsx, src/stories/pages/joinPage/index.jsx, src/stories/pages/joinPage/page1.jsx, src/stories/pages/loginPage/index.jsx
=> [feat] 본인인증에 이용한 사용자 정보 자동로딩

src/hooks/queries/userQueries.js, src/stories/pages/IdentifyPage/page3.jsx
=> [fix] 회원가입 SMS 인증 에러 수정

src/App.js, src/hooks/queries/userQueries.js, src/stories/pages/prodDetail/index.jsx, src/stories/pages/savingsPage/index.jsx, src/stories/pages/savingsPage/page1.jsx
=> [feat] 적금 상품의 최소 가입 금액 받아 입력값 유효성 체크

src/stories/atoms/accSelectBox/index.js, src/stories/molecules/mediumInput/index.js, src/stories/pages/savingsPage/page1.jsx, src/stories/pages/savingsPage/page2.jsx
=> [feat] 내 계좌 목록 조회 및 선택

.github/workflows/Github-Actions-FE.yml
Github Actions 빌드 시 AWS 보안규칙 추가 로직 삭제
=> [fix] ssh 포트 보안규칙 추가 로직 제거

src/App.js, src/api/productApi.js, src/hooks/queries/productQueries.js, src/stories/molecules/prodButtons/index.js, src/stories/pages/productPage/index.jsx
상품 종류 별 api 받아오기
상품 종류 버튼 별로 값 교체하기
화면에 구현
- closes #170 
깃 충돌 행결 하다가 커밋 좀 몇 번 하게 됐습니다,,,
=> [feat] 상품 목록 페이지 내 종류 별 나열

src/stories/atoms/accSelectBox/index.js, src/stories/pages/savingsPage/index.jsx, src/stories/pages/savingsPage/page1.jsx, src/stories/pages/savingsPage/page2.jsx, src/stories/pages/savingsPage/page3.jsx, src/stories/pages/savingsPage/page4.jsx
=> [feat] 적금 상품 자동이체일, 최초 저축 금액 설정

public/index.html, src/routes/noLayoutRouter.js, src/stories/atoms/mediumButton/index.js, src/stories/molecules/mainCarousel/index.js, src/stories/pages/mainPage/index.jsx, src/stories/pages/pwdPage/index.js, src/stories/pages/pwdPage/index.stories.jsx
Pwd 페이지 비밀번호 Popup + 비밀번호 전송 기능을 구현하고 해당 작업에 필요한 자동번역 disable과 Img alt 속성 추가 진행
=> [feat] mainPage Product 이체하기 버튼 Action 추가

src/api/userApi.js, src/constants/products.js, src/hooks/queries/userQueries.js, src/stories/pages/IdentifyPage/page2.jsx, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page2.jsx, src/stories/pages/loanPage/page3.jsx, src/stories/pages/savingsPage/index.jsx
- 직장 정보 수정
- 직장 종류 입력에 따른 페이지 이동 분리
- 학생/군인, 무직 -> 직장 입력 페이지를 이동하지 않고 바로 이동
- 나머지는 직장 입력 페이지로 이동
- closes #174
=> [feat] 대출 신용도 확인 - 직장 api 통신

src/stories/pages/pwdPage/index.js, src/stories/pages/pwdPage/index.stories.jsx, src/stories/pages/savingsPage/page4.jsx
=> [feat] 계좌 비밀번호 입력, 재입력 팝업창 플로우

src/api/productApi.js, src/hooks/queries/productQueries.js, src/routes/subLayoutRouter.js, src/stories/molecules/prodButtons/index.js, src/stories/molecules/searchBar/index.js, src/stories/pages/productPage/index.jsx, src/stories/pages/refuseLoanPage/index.jsx
- closes #176 
콘솔 로그 안 빼놔서 커밋 한 번 더 함
=> [feat] 상품 페이지 내 검색 기능 및 대출 가입 실패 페이지

src/api/accountApi.js, src/constants/products.js, src/hooks/queries/accountQueries.js, src/stories/molecules/mainCarousel/index.js, src/stories/pages/pwdPage/index.js, src/stories/pages/savingsPage/page4.jsx
=> [feat] 적금 상품 api 통신

src/stories/organisms/prodBenefit/index.js
=> [fix] 예적금 가입 시 예상 혜택 문구 수정

src/constants/products.js, src/hooks/queries/accountQueries.js, src/routes/subLayoutRouter.js, src/stories/pages/depositPage/index.jsx, src/stories/pages/depositPage/page1.jsx, src/stories/pages/depositPage/page2.jsx, src/stories/pages/savingsPage/page3.jsx, src/stories/pages/savingsPage/page4.jsx
=> [feat] 예금 가입 api 통신, 이체한도 초과 시 에러 핸들링

src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page4.jsx, src/stories/pages/loanPage/page5.jsx, src/stories/pages/loanPage/page6.jsx
=> [feat] 대출 플로우 및 api 통신

src/api/accountApi.js, src/hooks/queries/accountQueries.js, src/routes/noLayoutRouter.js, src/stories/molecules/blueHeaderBar/index.js, src/stories/pages/accHistoryPage/index.jsx, src/stories/pages/bottomPages/accountClosePage/index.js, src/stories/pages/bottomPages/accountClosePage/index.stories.jsx
=> [feat] 계좌해지

src/api/accountApi.js, src/constants/password.js, src/globalFunc/formatter.js, src/hooks/queries/accountQueries.js, src/index.js, src/stories/molecules/mainCarousel/index.js, src/stories/pages/accHistoryPage/index.jsx, src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/pwdPage/index.stories.jsx, src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js
=> [feat] 계좌이체 기능 구현

src/stories/molecules/mainCarousel/index.js
=> [fix] mainCarousel 좌우 컨트롤러 표시 이슈 해결

src/stories/molecules/accountItem/index.js, src/stories/molecules/mainCarousel/index.js, src/stories/pages/accountPage/index.jsx, src/stories/pages/mainPage/index.jsx
=> [feat] 내 계좌 리스트에서 메인계좌만 스타일 다르게 설정, 메인 케러셀에서 메인 계좌를 처음 뜨게 지정

src/routes/subLayoutRouter.js, src/stories/pages/checkingPage/index.jsx, src/stories/pages/prodDetail/index.jsx
=> [feat] 입출금 계좌 가입 구현

src/stories/pages/accHistoryPage/index.jsx, src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/checkingPage/index.jsx, src/stories/pages/depositPage/page2.jsx, src/stories/pages/loanPage/page6.jsx, src/stories/pages/pwdPage/index.js, src/stories/pages/pwdPage/index.stories.jsx, src/stories/pages/savingsPage/page4.jsx
parameter 를 사용해 비밀번호 입력 팝업 횟수 제한 적용
=> [feat] 비밀번호 입력 횟수 지정 기능 구현

src/stories/atoms/input/index.js, src/stories/pages/loginPage/index.jsx
- 
onKeyDown() 에서 Enter key 입력을 받을 경우 form 이 제출되도록 구현
=> [feat] 비밀번호 입력 시 Enter키로 form 제출 구현

src/constants/password.js, src/stories/pages/bottomPages/BottomSuccessPage/index.js, src/stories/pages/bottomPages/BottomSuccessPage/index.stories.jsx, src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/checkingPage/index.jsx, src/stories/pages/transferPage/page2.js
=> [feat] 계좌 개설 성공 바텀시트 구현

src/constants/password.js
=> [chore] password 페이지 popup 위치 수정

src/routes/mainLayoutRouter.js, src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/frontPage/index.jsx
=> [chore] 인덱스 라우팅 / 회원가입 라우팅 / Alert 디자인 변경

src/api/userApi.js, src/hooks/queries/userQueries.js, src/routes/noLayoutRouter.js, src/stories/pages/fixMyPage/index.js
회원 정보 수정
주거래 계좌, 일일 이체 한도만 수정 가능
변경시 계정 비밀번호 입력(비밀번호 팝업 x)
- closes #217
=> [feat] 회원 정보 수정

src/stories/molecules/mainCarousel/index.js
=> [feat] 계좌 캐러셀 조회하기

src/stories/atoms/prodItem/index.js, src/stories/organisms/prodContainer/index.js, src/stories/organisms/productList/index.js, src/stories/pages/mainPage/index.jsx, src/stories/pages/productPage/index.jsx
=> [fix] 데이터 로딩 이전 렌더링 시도 이슈

src/stories/organisms/popularProd/index.js
=> [feat] 인기상품 캐러셀 클릭 시 해당상품의 상세페이지 이동

src/stories/molecules/product/index.js
=> [fix] 입출금 상품의 경우 가입기간 제한없음

src/stories/molecules/headerBar/index.js
=> [feat] 헤더바 뒤로 가기

src/stories/molecules/headerBar/index.js
=> [ADD] 헤더 바 뒤로가기 버튼 마우스 포인터 변경

src/stories/pages/fixMyPage/index.js
=> [fix] 회원 정보 수정 후 마이페이지 이동 시차 추가

src/api/userApi.js, src/hooks/queries/userQueries.js, src/routes/subLayoutRouter.js, src/stories/pages/fixMyPage/index.js, src/stories/pages/tempPwdPage/index.jsx
=> [feat] 임시 비밀번호 재발급 및 비밀번호 수정

src/api/userApi.js, src/hooks/queries/userQueries.js, src/stories/organisms/prodContainer/index.js
=> [fix] 토큰 재발급 버그 수정

src/App.js, src/api/userApi.js, src/hooks/queries/userQueries.js, src/routes/noLayoutRouter.js, src/stories/pages/accHistoryPage/index.jsx, src/stories/pages/findIdPage/index.js, src/stories/pages/loginPage/index.jsx
=> [feat] 아이디 찾기 - 이메일 인증을 통해 구현

src/stories/pages/tempPwdPage/index.jsx
임시 비밀번호 발금 Alert 모달 추가
window open으로 바꾼 이후 자동 close() 기능 추가
=> [add] refactor - 비밀번호 찾기 완료 이후 로직 수정

src/api/userApi.js, src/stories/molecules/blueHeaderBar/index.js
=> [fix] 계좌 거래내역 조회 백 버튼 안먹음

src/routes/noLayoutRouter.js, src/routes/subLayoutRouter.js, src/stories/pages/accountPage/index.jsx, src/stories/pages/loanPage/page6.jsx, src/stories/pages/productMainPage/index.jsx, src/stories/pages/savingsPage/page4.jsx, src/stories/pages/transferPage/page2.js
=> [fix] 적금가입 및 상품 메인 헤더 바

.gitignore, package-lock.json, package.json, server/index.js, src/routes/noLayoutRouter.js, src/stories/pages/audioRecordPage/index.jsx, src/stories/pages/audioRecordPage/index.stories.jsx, src/utils/token_util.js
- 음성 인식 서비스 버튼 구현
- 음성 인식 후 text로 변환하여 AI 서버에 전송하고
- 변환된 값을 반환받음
- 여러 라이브러리 설치
- express node 서버 코드 추가
- !! .env 파일 만들어서 사용하세요 !!
=> [feat] 음성 인식 서비스 버튼 구현

src/App.js
프론트(인덱스 페이지) 로그아웃 시 리다이렉트 문제 해결
=> [fix] front page redirect exclude

package-lock.json, src/stories/pages/audioRecordPage/index.jsx, src/stories/pages/savingsPage/page3.jsx, src/stories/pages/transferPage/index.js, src/stories/pages/transferPage/page1.js
=> [feat] 자동이체 송금 계좌 AI 음성인식 자동 입력

src/routes/noLayoutRouter.js, src/routes/subLayoutRouter.js, src/stories/molecules/bottomStickyButton/index.js, src/stories/pages/accHistoryPage/index.jsx, src/stories/pages/accountPage/index.jsx, src/stories/pages/fixMyPage/index.js, src/stories/pages/frontPage/index.jsx, src/stories/pages/loanPage/index.jsx, src/stories/pages/loanPage/page2.jsx, src/stories/pages/loanPage/page3.jsx, src/stories/pages/loanPage/page4.jsx, src/stories/pages/loanPage/page5.jsx, src/stories/pages/loanPage/page6.jsx, src/stories/pages/myPage/index.js, src/stories/pages/prodDetailPage/index.jsx, src/stories/pages/productMainPage/index.jsx, src/stories/pages/productPage/index.jsx, src/stories/pages/savingsPage/page3.jsx, src/stories/pages/tempPwdPage/index.jsx, src/stories/pages/transferAccountPage/index.js, src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js, src/stories/templates/SubLayout.js
=> [fix] 화면 너비 640px 좌측 고정

src/stories/molecules/searchBar/index.js, src/stories/pages/productPage/index.jsx
=> [feat] 전체 상품 목록 페이지 버그 수정

src/stories/pages/fixMyPage/index.js, src/stories/pages/myPage/index.js
=> [fix] 개인정보 주거래 계좌 목록 토글로 변경

src/stories/pages/transferPage/index.js
=> [fix] 페이지 이동시 result value 초기화

src/App.js, src/routes/noLayoutRouter.js, src/stories/atoms/voiceVisual/index.js, src/stories/organisms/videoComp/index.js, src/stories/organisms/videoComp/index.stories.jsx, src/stories/organisms/voiceServiceComp/index.jsx, src/stories/organisms/voiceServiceComp/index.stories.jsx, src/stories/pages/mainPage/index.jsx, src/stories/pages/transferAccountPage/index.js, src/stories/pages/transferPage/index.js, src/stories/templates/MainLayout.js, tailwind.config.js
메인 Layout width 조정
AudioRecordPage -> VoiceServiceComp로 변경
Video Component 구현
MainPage 음성인식 / 영상 재생 기능 구현
=> [feat] 음성인식 컴포넌트 리팩토링 / 영상 재생 컴포넌트 구현 /메인 페이지 음성인식, 영상 재생 구현

src/routes/noLayoutRouter.js, src/stories/pages/InfoPage/bancassurancePage.jsx, src/stories/pages/InfoPage/precautionPage.jsx, src/stories/pages/mainPage/index.jsx, tailwind.config.js
=> [feat] [feat] 금융상식톡톡 - 신용대출 전 유의사항 정보성 페이지

src/stories/molecules/headerBar/index.js, src/stories/molecules/mediumInput/index.js, src/stories/pages/depositPage/index.jsx, src/stories/pages/depositPage/page1.jsx, src/stories/pages/depositPage/page2.jsx
=> [feat] 예금 상품 가입 ai 연결

src/App.js, src/stories/pages/depositPage/index.jsx, src/stories/pages/depositPage/page1.jsx, src/stories/pages/transferPage/index.js, src/stories/pages/transferPage/page1.js
=> [fix] 매 달 저축 금액 최소 납입금액 버그 수정, 저축 금액 음성 재입력

src/stories/pages/savingsPage/page1.jsx
=> [fix] Saving Page 저축 금액 표시 Error

src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/depositPage/index.jsx, src/stories/pages/depositPage/page2.jsx, src/stories/pages/transferPage/index.js, src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js
=> [feat] 계좌 이체 음성인식 ai 통신

src/App.js, src/stories/atoms/voiceVisual/index.js, src/stories/organisms/bottomSheet/index.js, src/stories/organisms/videoComp/index.js, src/stories/organisms/voiceServiceComp/index.jsx, src/stories/pages/checkingPage/index.jsx, src/stories/pages/mainPage/index.jsx, src/stories/pages/pwdPage/index.js, src/stories/pages/transferAccountPage/index.js, src/stories/pages/transferPage/index.js
[[feat] 영상 재생 종료 이후 자동 마이크 입력 기능 구현](https://github.com/BangCrush/BankAI-Frontend/commit/dc2ad159ccffdf3e26b5a46d71a51d696c2e3220)
[[refactor] 바텀시트 Backdrop 사이즈 / 위치 조정](https://github.com/BangCrush/BankAI-Frontend/commit/771afbeaab6cbede186f4d09c9235f09497e4b7c)
[[feat] Introduct main page 영상 적용](https://github.com/BangCrush/BankAI-Frontend/commit/4f5abef81d8dd5c0986a0bb862d13fc0f4be0d09)
=> [feat] 영상 재생 종료 이후 자동 마이크 입력 기능 구현

src/App.js, src/stories/organisms/videoComp/index.js, src/stories/organisms/voiceServiceComp/index.jsx
=> [design] ai 음성 캐릭터 사이즈 조정

src/App.js, src/stories/organisms/autoPlayToggle/index.js, src/stories/organisms/videoComp/index.js, src/stories/pages/transferAccountPage/index.js
- 영상 자동 재생 토글 버튼
- 현재 작업 중. 작업 중인 내용 중간 업로드.
=> [feat] 영상 자동 재생 토글 버튼

src/App.js, src/stories/organisms/autoPlayToggle/index.js, src/stories/organisms/videoComp/index.js
- 영상 자동 재생 토글 버튼 기본값 setting 기능 작동하지 않는 이슈 해결
- 변수명 변경: alignment -> autoPlay
=> [fix] 영상 자동 재생 토글 버튼 기본값 setting 기능

src/stories/organisms/videoComp/index.js
=> [fix] merge 과정에서 생긴 중복 코드 제거

src/stories/pages/productMainPage/index.jsx
상품 타입 ( 입출금 / 예금 / 적금 / 대출) 별 상품 보기 페이지로
음성인식 기능을 통해 이동
=> [feat] 상품 타입 음성 검색 기능 구현

src/api/userApi.js, src/stories/pages/mainPage/index.jsx, src/stories/pages/transferPage/index.js
[오늘의 내 송금 금액 API 호출 로직 작성](https://github.com/BangCrush/BankAI-Frontend/commit/5af6bd11d9ba1cf09dab24da4e4323919a70f078)
=> [feat] 오늘의 내 송금 금액 API 호출 로직 작성

src/stories/pages/transferAccountPage/index.js
[[fix] 계좌이체 가능 계좌 페이지에서 계좌 클릭 시 계좌이체 화면으로 이동](https://github.com/BangCrush/BankAI-Frontend/commit/08121bbff3293f014d58a8f1fb913ec7fc211856)
[[fix] Transfer Account Page 의 useEffect 의존성 정리 및 무한 렌더링 이슈 해결](https://github.com/BangCrush/BankAI-Frontend/commit/fe26df2f844c28d0ac7e0c01ca1e36739cc2590c)
=> [fix] 계좌이체 이전 이체 가능 계좌 페이지 관련 이슈 해결

src/stories/organisms/videoComp/index.js
[[fix] play() interrupted by request 이슈 해결](https://github.com/BangCrush/BankAI-Frontend/commit/60b0a27358ebefd8109f9ce65b05b968027e8eca)
useEffect() 의존성 수정 및 내부 함수 호출 구조 변경을 통한 재생 Interrupt 해결
=> [fix] play() interrupted by request 이슈 해결

src/stories/pages/transferAccountPage/index.js
계좌 이름을 음성으로 입력하면 자동으로 이동하는 로직 작성
=> [fix] 무한 렌더링 이슈 해결에 따른 계좌이체 페이지 이동 로직 변경

src/App.js, src/stories/pages/depositPage/index.jsx, src/stories/pages/mainPage/index.jsx, src/stories/pages/productMainPage/index.jsx, src/stories/pages/pwdPage/index.js, src/stories/pages/transferAccountPage/index.js, src/stories/pages/transferPage/index.js, src/stories/pages/transferPage/page1.js, src/stories/pages/transferPage/page2.js
- 계좌 이체 AI 서비스 계좌 번호 음성 입력 시 이체 금액에 계좌 번호가 입력되는 버그 수정
- AI 음성 서비스를 사용하는 모든 페이지에서 컴포넌트 mount 시 App.js의 result 값 null로 초기화
- 금액 음성 재입력 시 띄워지는 alert 삭제
=> [fix] 계좌 이체 AI 서비스 버그 수정

src/App.js
음성인식 토글 시 Video 재생 상태를 동시에 초기화하여 비디오가 끝날 때만 실행되는 음성 녹음 기능이 의도한 대로 작동하도록  적용
=> [fix] OFF 버튼 적용 시 마이크 입력 상태 초기화 오류 해결

src/stories/pages/bottomPages/transferCheckPage/index.js, src/stories/pages/transferPage/page2.js
기존에 금액확인과 이체 (비밀번호 확인) 과정이 하나의 음성으로 동시에 진행되었던 방식을 변경하여
금액을 먼저 확인하고, 이후에 비밀번호를 확인하는 방식으로 로직을 변경하였음
=> [fix] 계좌이체 음성인식 로직 수정

server/index.js, src/stories/pages/mainPage/index.jsx
한국수출입은행 Open API를 활용하여 사용자의 음성 입력에 따른 당일 환율 정보를 음성으로 출력하는 기능 구현
=> [feat] 오늘 환율 정보 확인하기 기능 구현

src/App.js, src/stories/organisms/videoComp/index.js, src/stories/pages/mainPage/index.jsx, src/stories/pages/prodDetailPage/index.jsx, src/stories/pages/productPage/index.jsx
[[feat] 음성인식을 통한 가입 상품 타입 지정 및 페이지 이동 구현](https://github.com/BangCrush/BankAI-Frontend/commit/84c32dc1b01c3de66ef0657e7547909253880267)
=> [feat] 음성인식을 통한 가입 상품 타입 지정 및 페이지 이동 구현

src/App.js, src/stories/organisms/voiceServiceComp/index.jsx, src/stories/pages/depositPage/index.jsx, src/stories/pages/depositPage/page1.jsx, src/stories/pages/depositPage/page2.jsx, src/stories/pages/mainPage/index.jsx, src/stories/pages/productMainPage/index.jsx, src/stories/pages/pwdPage/index.js
[[fix] 상품 가입 비정상 동작 이슈 해결](https://github.com/BangCrush/BankAI-Frontend/commit/e824d5af4a2b239537a5207fc885bce2635ee807)
=> [fix] 상품 가입 비정상 동작 이슈 해결
